version: 1.0.0
services:
  - mysql

variables:
  global:
    COMPOSER_BIN: $SOURCE_DIR/vendor/bin
    BLT_DIR: $SOURCE_DIR/vendor/acquia/blt

events:
  build:
    steps:
        - setup-env:
            type: script
            script:
              - composer validate --no-check-all --ansi
              - composer install --ansi
              - source ${BLT_DIR}/scripts/pipelines/setup_env
        - validate:
            type: script
            script:
              - source ${BLT_DIR}/scripts/pipelines/validate
        - setup-app:
            type: script
            script:
              - source ${BLT_DIR}/scripts/pipelines/setup_app
        - tests:
            type: script
            script:
#              - source ${BLT_DIR}/scripts/pipelines/tests
              - cd $SOURCE_DIR/docroot
              - sleep 10
              # Run a specific Lightning test:
              # - Panelizer is enabled for landing pages (1e244c89)
              - cat $SOURCE_DIR/tests/behat/local.yml
              - ../vendor/bin/behat --config $SOURCE_DIR/tests/behat/local.yml --tags=paragraphs
        - build-artifact:
            type: script
            script:
              - source ${BLT_DIR}/scripts/pipelines/build_artifact
        - deploy:
            script:
              - pipelines-deploy
  pr-merged:
    steps:
      - deploy:
          script:
            - pipelines-deploy
  pr-closed:
    steps:
      - deploy:
          script:
            - pipelines-deploy
